# Generated by Django 5.1.6 on 2025-04-15 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('mood', models.IntegerField(choices=[(1, 'SuperHappy'), (2, 'Happy'), (3, 'Satisfied'), (4, 'Funny'), (5, 'Loving'), (6, 'Normal'), (7, 'Nervous'), (8, 'Sad'), (9, 'Unsatisfied'), (10, 'Crying'), (11, 'Angry')], default=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('important', models.BooleanField(default=False)),
            ],
        ),
    ]
