# Generated by Django 5.1.6 on 2025-04-18 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diaries', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notes',
            old_name='description',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='notes',
            old_name='important',
            new_name='is_important',
        ),
    ]
